### ISSUE TITLE
bundle.js not found

### ISSUE THREAD

**Issue by thiagodp** [phosphorjs/phosphide-example#23]
Accessing 127.0.0.1:8080 returns a 404 for `bundle.js`:

![image](https://cloud.githubusercontent.com/assets/2997844/23049911/42d2adc8-f4a6-11e6-9af6-3b6920be8197.png)

Build error:
```
application/index.ts(45,17): error TS2339: Property 'keymap' does not exist on type 'IShortcutManager'
```
`npm-debug.log`

```
11 silly lifecycle   'tsc --project red && tsc --project green && tsc --project yellow && tsc --project blue && tsc --project editor && tsc --project application && webpack --config webpack.conf.js' ]
12 silly lifecycle phosphide-example@0.0.2~build: Returned: code: 1  signal: null
13 info lifecycle phosphide-example@0.0.2~build: Failed to exec build script
14 verbose stack Error: phosphide-example@0.0.2 build: `tsc --project red && tsc --project green && tsc --project yellow && tsc --project blue && tsc --project editor && tsc --project application && webpack --config webpack.conf.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\dev\nodejs\node_modules\npm\lib\utils\lifecycle.js:242:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\dev\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid phosphide-example@0.0.2
16 verbose cwd C:\dev\wamp\www\phosphide-example
17 error Windows_NT 10.0.14393
18 error argv "C:\\dev\\nodejs\\node.exe" "C:\\dev\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
19 error node v6.7.0
20 error npm  v3.10.3
21 error code ELIFECYCLE
22 error phosphide-example@0.0.2 build: `tsc --project red && tsc --project green && tsc --project yellow && tsc --project blue && tsc --project editor && tsc --project application && webpack --config webpack.conf.js`
22 error Exit status 1
23 error Failed at the phosphide-example@0.0.2 build script 'tsc --project red && tsc --project green && tsc --project yellow && tsc --project blue && tsc --project editor && tsc --project application && webpack --config webpack.conf.js'.
```

@ Windows 10, node v6.7.0, npm 3.10.3, Chrome 56

**Comment by sccolbert** [comment]
This module/package is very old, and will be deleted soon. All development has moved to the main `phosphor` repo. 

The best in-the-wild example for using Phosphor to its fullest is JupyterLab:
https://github.com/jupyterlab/jupyterlab

Sorry for the confusion!

**Comment by thiagodp** [comment]
Thanks for the quick answer. I've just watch a JupyterLab video (http://blog.jupyter.org/2016/07/14/jupyter-lab-alpha/) ;)
